### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by FezVrasta** [alienfast/picker.js#1]
How can I help you with this date picker project?

I can’t find any test section or anything to see an actual result to help the development process.

Thanks!

**Comment by rosskevin** [comment]
Hey Federico,  I'm still converting the original,  which has tests,  but the biggest help for me would be if you could use the v4 codepen and mockup the markup/styles to meet the spec views. I'll do some more on it tonight and should be done tomorrow with the baseline conversion.  If you have a sample I could plugin, that would be fantastic. 

I'd like to convert tests to mocha or jasmine,  I'm also a novice there.  Anything build related,  just let me know and I can take care of those additions quickly. 

Once I've got something presenting, I'm sure you'll also be able to tweak the popper.js use.

**Comment by FezVrasta** [comment]
Maybe I've missed something but what's wrong with http://t00rk.github.io/bootstrap-material-datetimepicker/ ?

**Comment by rosskevin** [comment]
- The look isn't far off but doesn't meet spec
- I'd like to support the broader range of options that bootstrap-datepicker does
- its a modal only,  and does not materialize from the input field itself on md to lg screens (seems disorienting and against material principles) 
- I'd like to leverage/reuse our work on bmd v4

Likewise,  bootstrap-datepicker concerns: 
- structurally getting it to work for bmd v4
- non-es2015 impl with lots of issues
- doesn't use momentjs, which is a big part of the impl (all date parsing,  formatting, and locales) 

Do you think these are valid?  I'm open to ideas or shifting strategies.

**Comment by FezVrasta** [comment]
Completely agree with you

**Comment by rosskevin** [comment]
Update readme:
https://github.com/alienfast/picker.js#why

I'd like to keep the structure the same where possible, though I'm planning to have pluggable templates.  The readme describes building, and the `sandbox/test.html` is the most basic example with BS3.

If someone wants to work ahead of me, snag the html generated for the picker inside `.popper` and create a codepen of a  proper picker with the [BMD v4 template](http://codepen.io/rosskevin/pen/eJMMVB)

**Comment by rosskevin** [comment]
BS3 is working, tests converted, code cleaned up.  I'm going to start a BS4 and BMD rendering and get far enough so I can work on the picker.js to develop a `Preset` so that we can just specify the targeted framework.

**Comment by rosskevin** [comment]
BS3, BS4 (could use styling help), and BMD4 are all working.

@FezVrasta BMD4 could specifically use help on the animated reveal/hide, but functionally and visually, it's all there and ready to go.
