### ISSUE TITLE
Empty row on top

### ISSUE THREAD

**Issue by FezVrasta** [alienfast/picker.js#10]
![image](https://cloud.githubusercontent.com/assets/5382443/14924778/68ab0372-0e44-11e6-9d00-4915cb4ce8b1.png)

**Comment by rosskevin** [comment]
This is a bug if we leave it as-is, depending on the decision on #9

**Comment by FezVrasta** [comment]
How #9 is related? Here we have a full row of empty cells, I wouldn't expect anything there.

**Comment by rosskevin** [comment]
previous month's days are there, just not visible.  If we display them in gray, this won't be a bug.  If we keep them hidden, this is a bug.

**Comment by FezVrasta** [comment]
I think they should be visible only if the first day of the month doesn't start at position 0

```
_ _ _ 1 2 3 4  // here we should display 29 30 31 1 2 3 4
1 2 3 4 5 6 7 // here we are okay, no rows before it
```

**Comment by rosskevin** [comment]
Yes, this is a bit wierd.  I agree, I toggled the vis on the `old` class, and dates are 24th - 30th on top row.  I think the algorithm always displays at least a few previous days, up to 7.
