### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by FezVrasta** [alienfast/picker.js#11]
After `npm i`

If I run `gulp` I get:

```
/Users/federicozivolo/.nvm/versions/node/v5.3.0/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/federicozivolo/.nvm/versions/node/v5.3.0/lib/node_modules/gulp/bin/gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
```

Am I missing something?

**Comment by rosskevin** [comment]
you are probably on gulp 3,  See https://github.com/alienfast/picker.js#basics

**Comment by rosskevin** [comment]
Also, just updated that doc, I usually run
`gulp rollup:iife:watch` in one term and `gulp css:watch` in another for speedy development.  `gulp js:watch` will also run tests.  It's down to personal preference.

**Comment by rosskevin** [comment]
^^^ this advice doesn't work since the site is using copied files from dist.  Stick to `js:watch` for now

**Comment by rosskevin** [comment]
I just committed a fix for dev, this will get you everything (and runs fast):

`gulp css:watch js:dev:watch`
